version: 2

jobs:
  deploy:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: sh build_docker.sh
      - run: docker run --rm -t public-tree-map-prod:latest ./upload_gcs.sh "${GOOGLE_PROJECT_ID}" "${GCLOUD_SERVICE_KEY}"
      - store_artifacts:
          path: tmp/log.txt
          destination: log.txt

workflows:
  version: 2
  commit:
    jobs:
      - deploy:
          filters:
            branches:
              only:
              - master
              - test-circleci
  nightly:
    triggers:
      - schedule:
          # Midnight PST is 8am UTC
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - deploy